
import { FC } from "react";

const HeroSection: FC = () => {
  return (
    <div className="">
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
      <h1>Hiiiiiii</h1>
    </div>
  );
};

export default HeroSection;
